#!/usr/bin/env bash

wget https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.26-202211231800/eclipse-SDK-4.26-linux-gtk-x86_64.tar.gz -O eclipse.tar.gz
sudo tar -xzf eclipse.tar.gz -C /
rm eclipse.tar.gz
echo "Eclipse downloaded and unpacked to /eclipse"