name: Generate CI Matrix from ci.jsonnet

on:
  workflow_dispatch:
    inputs:
      jobs_to_run:
        type: string
        description: Job selection (Python regex)
        required: false

jobs:
  generate-tier1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      TARGET: tier1
      JOBS: ${{ inputs.jobs_to_run }}
    steps: &generate_matrix
      - uses: actions/checkout@v4
      - name: Download sjsonnet
        run: |
          curl -L -o sjsonnet https://github.com/databricks/sjsonnet/releases/download/0.5.7/sjsonnet-0.5.7-linux-x86_64
          chmod +x sjsonnet
      - name: Extract job matrix
        id: set-matrix
        run: |
          python3 .github/scripts/extract_matrix.py ./sjsonnet ./ci.jsonnet ${TARGET} ${JOBS} > matrix.json
          cat matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  generate-tier2:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      TARGET: tier2
      JOBS: ${{ inputs.jobs_to_run }}
    steps: *generate_matrix

  generate-tier3:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      TARGET: tier3
      JOBS: ${{ inputs.jobs_to_run }}
    steps: *generate_matrix

  tier1:
    needs: generate-tier1
    runs-on: ${{ matrix.os }}
    env: ${{ matrix.env }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-tier1.outputs.matrix) }}
    steps: &buildsteps
      - uses: actions/checkout@main

      # Set up environment to match internal CI
      - name: Setup Unix paths like on buildbot CI (see actions/upload-artifact#176)
        if: runner.os != 'Windows'
        run: |
          ln -s $(pwd) ../main || true
          cd ..
          echo "PARENT_DIRECTORY=$(pwd)" >> $GITHUB_ENV
      - name: Set Windows parent directory absolute path (see actions/upload-artifact#176)
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType SymbolicLink -Value $PWD -Path $(Resolve-Path .. | Join-Path -ChildPath "main") -ErrorAction SilentlyContinue
          cd ..
          "PARENT_DIRECTORY=$PWD" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      # Set up Python and packages
      - uses: actions/setup-python@v6
        if: ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install python packages on Unix
        if: ${{ runner.os != 'Windows' && matrix.python_packages }}
        run: |
          for pkg in ${{ matrix.python_packages }}; do
              pip install "$pkg" || true
          done
      - name: Install system packages on Windows
        if: ${{ runner.os == 'Windows' && matrix.python_packages }}
        run: |
          foreach ($pkg in ${{ matrix.python_packages }}) {
            pip install "$pkg"
          }

      - name: Install system packages on Linux
        if: ${{ runner.os == 'Linux' && matrix.system_packages }}
        run: |
          sudo apt-get -qq update
          for pkg in ${{ matrix.system_packages }}; do
              sudo apt-get -qq install "$pkg" || true
          done
      - name: Install system packages on macOS
        if: ${{ runner.os == 'macOS' && matrix.system_packages }}
        run: |
          brew update
          for pkg in ${{ matrix.system_packages }}; do
              brew install "$pkg" || true
          done
      - name: Install system packages on Windows
        if: ${{ runner.os == 'Windows' && matrix.system_packages }}
        run: |
          foreach ($pkg in ${{ matrix.system_packages }}) {
            choco install "$pkg" -y -ErrorAction SilentlyContinue
          }

      - name: Get mx, buildtools, and labsjdk
        if: ${{ matrix.mx_version }}
        run: |
          git clone https://github.com/graalvm/mx
          mx/mx fetch-jdk -A --jdk-id labsjdk-ce-latest
          git -C mx checkout ${{ matrix.mx_version }}
      - name: Setup mx and JAVA_HOME on Unix
        if: ${{ runner.os != 'Windows' && matrix.mx_version }}
        run: |
          echo "$(pwd)/mx/" >> "$GITHUB_PATH"
          echo "$(pwd)/.github/scripts/" >> "$GITHUB_PATH"
          echo "JAVA_HOME=$HOME/.mx/jdks/labsjdk-ce-latest" >> "$GITHUB_ENV"
          echo "JVMCI_VERSION_CHECK=ignore" >> "$GITHUB_ENV"
      - name: Setup mx and JAVA_HOME on Windows
        if: ${{ runner.os == 'Windows' && matrix.mx_version }}
        run: |
          "$PWD/mx" | Out-File -FilePath "$env:GITHUB_PATH" -Append
          "$PWD/.github/scripts" | Out-File -FilePath "$env:GITHUB_PATH" -Append
          "JAVA_HOME=$HOME/.ms/jdks/labsjdk-ce-latest" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "JVMCI_VERSION_CHECK=ignore" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Download artifacts
        uses: actions/download-artifact@v5
        if: ${{ matrix.require_artifact }}
        with:
          pattern: ${{ matrix.require_artifact[0] }}
          path: ${{ matrix.require_artifact[1] }}
          merge-multiple: true

      - name: Setup
        if: ${{ matrix.setup_steps }}
        run: |
          env
          ${{ matrix.setup_steps }}
      - name: Run
        if: ${{ matrix.run_steps }}
        run: |
          ${{ matrix.run_steps }}

      - name: Upload artifacts
        if: ${{ matrix.provide_artifact }}
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.provide_artifact[0] }}
          path: |
            ${{ matrix.provide_artifact[1] }}
          retention-days: 1

      - name: Upload logs
        if: ${{ matrix.logs }}
        uses: actions/upload-artifact@v5
        with:
          name: ${{ format('{0}_logs', matrix.name) }}
          path: |
            ${{ matrix.logs }}
          retention-days: 15

  tier2:
    if: ${{ success() || inputs.jobs_to_run }}
    needs: [generate-tier2, tier1]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-tier2.outputs.matrix) }}
    steps: *buildsteps

  tier3:
    if: ${{ success() || inputs.jobs_to_run }}
    needs: [generate-tier3, tier2]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-tier3.outputs.matrix) }}
    steps: *buildsteps
