name: Generate CI Matrix from ci.jsonnet

on:
  workflow_dispatch:

jobs:
  generate-tier1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      TARGET: tier1
    steps: &generate_matrix
      - uses: actions/checkout@v4
      - name: Download sjsonnet
        run: |
          curl -L -o sjsonnet https://github.com/databricks/sjsonnet/releases/download/0.5.7/sjsonnet-0.5.7-linux-x86_64
          chmod +x sjsonnet
      - name: Extract job matrix
        id: set-matrix
        run: |
          python3 .github/scripts/extract_matrix.py ./sjsonnet ./ci.jsonnet ${TARGET} > matrix.json
          cat matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  generate-tier2:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      TARGET: tier2
    steps: *generate_matrix

  generate-tier3:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      TARGET: tier3
    steps: *generate_matrix

  tier1:
    needs: generate-tier1
    runs-on: ${{ matrix.os }}
    env: ${{ matrix.env }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-tier1.outputs.matrix) }}
    steps: &buildsteps
      - uses: actions/checkout@main
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install python packages on Unix
        if: runner.os != 'Windows'
        run: |
          for pkg in ${{ matrix.python_packages }}; do
              pip install "$pkg" || true
          done
      - name: Install system packages on Windows
        if: runner.os == 'Windows'
        run: |
          foreach ($pkg in ${{ matrix.python_packages }}) {
            pip install "$pkg"
          }
      - name: Get mx
        run: |
          git clone https://github.com/graalvm/mx
          # git -C mx checkout ${{ matrix.mx_version }}
      - name: Put mx and utils on Unix PATH
        if: runner.os != 'Windows'
        run: |
          echo "$(pwd)/mx/" >> "$GITHUB_PATH"
          cp .github/scripts/set-export mx/
          cp .github/scripts/unpack-artifact mx/
      - name: Put mx and utils on Windows PATH
        if: runner.os == 'Windows'
        run: |
          "$PWD/mx" | Out-File -FilePath "$env:GITHUB_PATH" -Append
          cp .github/scripts/set-export.cmd mx/
          cp .github/scripts/unpack-artifact.cmd mx/

      - name: Install system packages on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -qq update
          for pkg in ${{ matrix.system_packages }}; do
              sudo apt-get -qq install "$pkg" || true
          done
      - name: Install system packages on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          for pkg in ${{ matrix.system_packages }}; do
              brew install "$pkg" || true
          done
      - name: Install system packages on Windows
        if: runner.os == 'Windows'
        run: |
          foreach ($pkg in ${{ matrix.system_packages }}) {
            choco install "$pkg" -y -ErrorAction SilentlyContinue
          }

      - name: Get labsjdk on Unix
        if: runner.os != 'Windows'
        run: |
          mx -p ../graal/vm fetch-jdk -A --jdk-id labsjdk-ce-latest
          echo "JAVA_HOME=$HOME/.mx/jdks/labsjdk-ce-latest" >> "$GITHUB_ENV"
          echo "JVMCI_VERSION_CHECK=ignore" >> "$GITHUB_ENV"
      - name: Get labsjdk on Windows
        if: runner.os == 'Windows'
        run: |
          mx -p ../graal/vm fetch-jdk -A --jdk-id labsjdk-ce-latest
          "JAVA_HOME=$HOME/.ms/jdks/labsjdk-ce-latest" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "JVMCI_VERSION_CHECK=ignore" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Download artifacts
        uses: actions/download-artifact@v5
        if: ${{ matrix.require_artifact }}
        with:
          pattern: ${{ matrix.require_artifact[0] }}
          path: ${{ matrix.require_artifact[1] }}
          merge-multiple: true

      - name: Setup
        run: ${{ matrix.setup_steps }}
      - name: Run
        run: ${{ matrix.run_steps }}

      - name: Upload artifacts
        if: ${{ matrix.provide_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.provide_artifact[0] }}
          path: ${{ matrix.provide_artifact[1] }}
          retention-days: 1

      - name: Upload logs
        if: ${{ matrix.logs }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name + "_logs" }}
          path: ${{ matrix.logs }}
          retention-days: 1

  tier2:
    if: ${{ always() }}
    needs: [generate-tier2, tier1]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-tier2.outputs.matrix) }}
    steps: *buildsteps

  tier3:
    if: ${{ always() }}
    needs: [generate-tier3, tier2]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-tier3.outputs.matrix) }}
    steps: *buildsteps
